services:
  - type: web
    name: pyretwwit
    runtime: python
    plan: free
    region: oregon  
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: MONGO_URI
        sync: false
      - key: X_USERNAME
        sync: false
      - key: X_EMAIL
        sync: false
      - key: X_PASSWORD
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      
